### ISSUE TITLE
Integrate exact match filter into cross hybridization filter

### ISSUE THREAD

**Issue by IsraMekki0** [HelmholtzAI-Consultants-Munich/oligo-designer-toolsuite#39]
The exact match filter already aggressively deleting oligos. The cross hybridization filter wouldn't remove anything if the exact match filter was already used

**Comment by lisa-sousa** [comment]
We should keep the exact match filter as a filter with apply function but also provide a "get_oligo_pair_hits" function like for the blast filter, to be able to use it for the crosshybridization filter. Do the same thing for Bowtie filters?
